### ISSUE TITLE
Support multiple ingress

### ISSUE THREAD

**Issue by boukadam** [BriceMichalski/mbcaas-chart#1]
Add the option to setup multiple ingresses for an application

```yaml
ingress:
  - host: bannershake-app.mbcode.cloud
    annotations:
      external-dns.alpha.kubernetes.io/hostname: bannershake-app.mbcode.cloud
      traefik.ingress.kubernetes.io/router.entrypoints: websecure
      traefik.ingress.kubernetes.io/router.tls.certresolver: letsencrypt
    paths:
      - path: /
        type: Prefix
        port: http
  - host: bannershake.com
     annotations:
       traefik.ingress.kubernetes.io/router.entrypoints: websecure
       traefik.ingress.kubernetes.io/router.tls.certresolver: letsencrypt
    paths:
      - path: /
        type: Prefix
        port: http
```
